org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20

minecraft_version=1.21.11
minecraft_version_range=[1.21.9,1.21.12)
neo_version=21.9.16-beta

mod_id=defaultdarkmodepatcher
mod_name=Default Dark Mode Patcher
mod_license=CC BY-NC-SA 4.0
mod_version=1.3.2
mod_group_id=com.aric3435.defaultdarkmodepatcher
